/**
 * Core data types for the Brain Dump RAG application
 *
 * @module types
 */

/**
 * Represents a thought/note stored in the application
 *
 * @interface Thought
 */
export interface Thought {
  /** Unique identifier for the thought */
  id: string;

  /** The main content/text of the thought */
  content: string;

  /** Timestamp when the thought was created (milliseconds since epoch) */
  createdAt: number;

  /** Optional tags for categorizing and filtering thoughts */
  tags: string[];

  /**
   * Vector embedding for semantic search
   * This field stores the embedding vector that enables RAG (Retrieval Augmented Generation)
   * The embedding is typically generated by an AI model and used for similarity search
   *
   * @optional
   */
  embedding?: number[];
}

/**
 * Application settings and configuration
 *
 * @interface AppSettings
 */
export interface AppSettings {
  /** OpenAI API key for AI model access */
  openaiApiKey?: string;

  /** Anthropic API key for Claude model access */
  anthropicApiKey?: string;

  /** Custom API URL endpoint override */
  apiUrl?: string;

  /** Name of the AI model to use (e.g., 'gpt-4', 'claude-3-opus') */
  modelName?: string;

  /**
   * Flag to enable/disable real AI model usage
   * When false, the app may use mock responses for testing
   *
   * @default false
   */
  useRealAI?: boolean;
}

/**
 * Database schema version information
 * Used for tracking and migrating data between different versions
 *
 * @interface SchemaVersion
 */
export interface SchemaVersion {
  /** Current schema version number */
  version: number;

  /** Timestamp of last migration */
  migratedAt?: number;
}

/**
 * Migration status for tracking localStorage to IndexedDB migration
 *
 * @interface MigrationStatus
 */
export interface MigrationStatus {
  /** Whether migration from localStorage has been completed */
  hasMigratedFromLocalStorage: boolean;

  /** Timestamp when migration was completed */
  migratedAt?: number;

  /** Number of thoughts migrated */
  thoughtsMigrated?: number;
}

/**
 * Error types for database operations
 *
 * @interface DatabaseError
 */
export interface DatabaseError extends Error {
  /** Error code for identifying the type of database error */
  code: 'NOT_FOUND' | 'CONSTRAINT_ERROR' | 'QUOTA_EXCEEDED' | 'UNKNOWN';

  /** Additional context about the error */
  details?: unknown;
}

/**
 * Result type for bulk operations
 *
 * @interface BulkOperationResult
 */
export interface BulkOperationResult<T> {
  /** Number of successfully processed items */
  successCount: number;

  /** Items that failed to process with their errors */
  failures: Array<{
    item: T;
    error: string;
  }>;
}

/**
 * Options for querying thoughts
 *
 * @interface ThoughtQueryOptions
 */
export interface ThoughtQueryOptions {
  /** Filter by tag(s) - multiple tags are OR'd together */
  tags?: string[];

  /** Search query string for content matching */
  searchQuery?: string;

  /** Maximum number of results to return */
  limit?: number;

  /** Number of results to skip for pagination */
  offset?: number;

  /** Sort order - 'asc' for oldest first, 'desc' for newest first */
  sortOrder?: 'asc' | 'desc';

  /** Filter by creation date range */
  dateRange?: {
    /** Start of date range (inclusive) */
    from?: number;
    /** End of date range (inclusive) */
    to?: number;
  };
}

/**
 * Vector similarity search result
 *
 * @interface SimilarThought
 */
export interface SimilarThought extends Thought {
  /** Similarity score (0-1, where 1 is identical) */
  similarity: number;
}

/**
 * RAG (Retrieval Augmented Generation) search options
 *
 * @interface RagSearchOptions
 */
export interface RagSearchOptions {
  /** Query text for semantic search */
  query: string;
  /** Maximum number of results to return */
  limit?: number;
  /** Minimum similarity threshold (0-1) */
  threshold?: number;
  /** Tags to filter by */
  tags?: string[];
}

/**
 * RAG search result with relevance score
 *
 * @interface RagSearchResult
 */
export interface RagSearchResult {
  /** The matching thought */
  thought: Thought;
  /** Similarity score (0-1) */
  similarity: number;
}

/**
 * Embedding computation options
 *
 * @interface EmbeddingOptions
 */
export interface EmbeddingOptions {
  /** Whether to compute embedding for the thought */
  computeEmbedding?: boolean;
  /** Callback for embedding progress updates */
  onProgress?: (progress: { progress: number; status: string }) => void;
}
